### ISSUE TITLE
Crash during startup with Polymer installed on 1.20.2

### ISSUE THREAD

**Issue by unilock** [badasintended/badpackets#11]
### Describe the issue

With both WTHIT and [Polymer](https://github.com/Patbox/polymer) installed, specifically on Minecraft 1.20.2, the game crashes almost immediately during startup.

### Log output and crash report

https://gist.github.com/unilock/5813a1dc03b76efebfa95d633744d1f1

### Additional context

- Minecraft `1.20.2`
- Fabric Loader `0.14.23`
- Fabric API `0.90.0+1.20.2`
- Bad Packets `fabric-0.5.1`
- WTHIT `fabric-9.0.0`
- Polymer `0.6.2+1.20.2`

The same crash occurs in both a client and dedicated server environment.

Maybe it's some sort of conflict between Bad Packets' and Polymer's mixins to CustomPayloadS2CPacket / ServerboundCustomPayloadPacket? ([Bad Packets](https://github.com/badasintended/badpackets/blob/30edd0d6601b08f47c7c891ff07a7214a0cddec8/src/main/java/lol/bai/badpackets/impl/mixin/AccessServerboundCustomPayloadPacket.java) / [Polymer](https://github.com/Patbox/polymer/blob/c279e4e64460abdc83101955268edcdab1a3451d/polymer-networking/src/main/java/eu/pb4/polymer/networking/mixin/CustomPayloadC2SPacketAccessor.java))

**Comment by unilock** [comment]
Now I'm getting another error during startup with *only* WTHIT + Bad Packets installed, specifically in a dedicated server environment.

```
Caused by: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for lol.bai.badpackets.impl.mixin.client.AccessClientboundCustomPayloadPacket. Mixin is defined in badpackets.mixins.json and cannot be referenced directly
```

Log: https://gist.github.com/unilock/e29fa480ee0111153570a38518829e2f

**Comment by deirn** [comment]
Ah, I think it because `AccessClientboundCustomPayloadPacket` is a client-only class getting loaded on server. 😅
