### ISSUE TITLE
crasher

### ISSUE THREAD

**Issue by joaoespanhol** [badasintended/badpackets#15]
log:
https://mclo.gs/v1i0Zdu

**Comment by deirn** [comment]
Did you even install the mod?

**Comment by joaoespanhol** [comment]
yes

**Comment by joaoespanhol** [comment]
i no have problem versionm: wthit-forge-4.13.5.jarEliminado
i have problem: last version w

**Comment by deirn** [comment]
Bad Packets, do you install it?

**Comment by joaoespanhol** [comment]
badpackets-forge-0.1.3.jar

> Bad Packets, do you install it?

badpackets-forge-0.1.3.jar

**Comment by deirn** [comment]
Then I'm not sure, there's nothing else on your log.

**Comment by joaoespanhol** [comment]
i fixe problem use wthit-forge-4.13.5.jar

:D
