### ISSUE TITLE
Server sent an invalid packet

### ISSUE THREAD

**Issue by GeorgeV220** [badasintended/badpackets#16]
When I'm trying to connect to a friend's server I get this error (1.20.4):
https://mclo.gs/w92kH8R#L982

**Comment by deirn** [comment]
Something is making Bad Packet's packet handler not being registered. To know what mod that is I need to know the list of mods that modify the vanilla class responsible for it.

Please run with `-Dmixin.debug.output=true` JVM argument and rerun until the error occurs again. Then, send me the content of `.minecraft/.mixin.out` **privately** to me via Discord. Join my server [here](https://bai.lol/discord) and DM `@deirn`.

**Comment by GeorgeV220** [comment]
I added this JVM argument to modrinth but no file with `.mixin.out` exists.

**Comment by deirn** [comment]
Oops, sorry it's `-Dmixin.debug.export=true`, not output.

**Comment by deirn** [comment]
ViaFabricPlus issue. https://github.com/ViaVersion/ViaFabricPlus/issues/359
