### ISSUE TITLE
Issue with Artifact Retrieval - 404 Error on Maven Repository

### ISSUE THREAD

**Issue by scattered-leaves** [badasintended/badpackets#17]
I am encountering an issue while attempting to fetch a specific artifact from your Maven repository at https://maven2.bai.lol. Specifically, I am trying to access the POM file for the badpackets-fabric module with version 0.4.3, located at https://maven2.bai.lol/lol/bai/badpackets/fabric-0.4.3/badpackets-fabric-0.4.3.pom. However, I consistently receive a 404 Not Found error upon accessing this URL.
This prevents me from smoothly incorporating the badpackets-fabric-0.4.3 dependency into my project's build process. As a result, I am unable to proceed with the integration and development relying on this package.
Given that English is not my primary language, I am using an AI translation tool to communicate this problem. Please forgive any linguistic inaccuracies in this message.

**Comment by deirn** [comment]
Ah. It seems like i forgot to add the sync task to the release workflow...

For now, you can use 0.4.1 version instead.

**Comment by scattered-leaves** [comment]
OK
